In [1]:
from pathlib import Path
import pandas as pd
from sklearn.metrics import confusion_matrix, classification_report
import numpy as np
from sklearn.preprocessing import StandardScaler
pd.options.display.float_format = '{:.0f}'.format

In [17]:
# data = Path('../Resources/diabetes.csv')

start_data = pd.read_csv('../Resources/cleaned.csv')
start_data.head()
start_data.columns


# 'Box Office Analysis' start_data['BoxOffice_Inf_Adj'][start_data['BoxOffice_Inf_Adj'] ]

Index(['Title', 'Rated', 'Released', 'Runtime', 'Genre', 'Director', 'Actors',
       'Language', 'Country', 'Awards', 'Metascore', 'imdbRating', 'imdbVotes',
       'imdbID', 'BoxOffice', 'Rotten_Tomatoes', 'R_Year', 'R_Month', 'R_Day',
       'Rounded Rating', 'Good_Movie', 'DRAMA', 'HORROR', 'MUSIC', 'THRILLER',
       'DOCUMENTARY', 'ANIMATION', 'ACTION', 'ADVENTURE', 'BIOGRAPHY',
       'COMEDY', 'FANTASY', 'MYSTERY', 'ROMANCE', 'SCI-FI', 'CRIME', 'FAMILY',
       'HISTORY', 'SPORT', 'WAR', 'MUSICAL', 'WESTERN', 'NEWS', 'REALITY-TV',
       'Unnamed: 44', 'GAME-SHOW', 'TALK-SHOW', 'BoxOffice_Inf_Adj'],
      dtype='object')

In [3]:
# start_data[[ 'imdbRating','Good_Movie']][start_data['Good_Movie'] == True]
# start_data['Runtime'] = start_data['Runtime'].str.replace(' min', '', regex=False).astype(int)
start_data['imdbVotes'] = start_data['imdbVotes'].str.replace(',', '', regex=False).astype(float)

In [4]:
model_data = start_data[start_data['R_Year'] >= 2010]

model_data = model_data[['Director','imdbVotes','Rated','R_Year','R_Month','R_Day','Runtime','Good_Movie',
       'DRAMA', 'HORROR', 'MUSIC', 'THRILLER',
       'DOCUMENTARY', 'ANIMATION', 'ACTION', 'ADVENTURE', 'BIOGRAPHY',
       'COMEDY', 'FANTASY', 'MYSTERY', 'ROMANCE', 'SCI-FI', 'CRIME', 'FAMILY',
       'HISTORY', 'SPORT', 'WAR', 'MUSICAL', 'WESTERN', 'NEWS']].copy()


model_data = model_data.fillna(0)
model_data

,Director,imdbVotes,Rated,R_Year,R_Month,R_Day,Runtime,Good_Movie,DRAMA,HORROR,...,ROMANCE,SCI-FI,CRIME,FAMILY,HISTORY,SPORT,WAR,MUSICAL,WESTERN,NEWS
0,Orson Welles,8188,R,2018,11,2,122,False,1,0,...,0,0,0,0,0,0,0,0,0,0
1,André Szöts,1801,Not Rated,2021,1,8,74,False,0,1,...,0,0,0,0,0,0,0,0,0,0
2,John Bailey,72,PG-13,2019,11,13,101,True,1,0,...,0,0,0,0,0,0,0,0,0,0
3,John Mulholland,100,Unrated,2013,9,27,120,False,0,0,...,0,0,0,0,0,0,0,0,0,0
4,Stuart Paul,151,TV-MA,2018,11,6,104,False,1,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17973,Joe Begos,9831,Not Rated,2020,2,14,92,False,0,1,...,0,0,1,0,0,0,0,0,0,0
17974,Geeta Malik,893,PG-13,2022,2,3,101,False,0,0,...,0,0,0,0,0,0,0,0,0,0
17975,Robert Fernandez,921,PG,2019,4,18,108,False,0,0,...,0,0,0,1,0,0,0,0,0,0
17976,Michael Dowse,14780,TV-MA,2020,4,3,88,False,0,0,...,0,0,1,0,0,0,0,0,0,0
17977,Sean Ellis,19650,R,2022,2,18,111,False,0,1,...,0,0,0,0,0,0,0,0,0,0

In [5]:
model_data = pd.get_dummies(model_data, columns=['Rated','R_Year','R_Month','R_Day','Director'])
scaler = StandardScaler()
y = model_data["Good_Movie"]
arr = scaler.fit_transform(model_data.copy())
df = pd.DataFrame(arr, columns=model_data.columns)
df

,imdbVotes,Runtime,Good_Movie,DRAMA,HORROR,MUSIC,THRILLER,DOCUMENTARY,ANIMATION,ACTION,...,Director_Zoe Quist,Director_Zoran Lisinac,Director_Zoë Kravitz,Director_Zu Quirke,Director_Álex de la Iglesia,Director_Álvaro Cáceres,Director_Èric Boadella,Director_Étienne Faure,Director_Étienne Sauret,Director_Óscar Ruiz Navia
0,-0,1,-0,1,-0,-0,-0,-1,-0,-0,...,-0,-0,-0,-0,-0,-0,-0,-0,-0,-0
1,-0,-1,-0,-1,2,5,2,-1,-0,-0,...,-0,-0,-0,-0,-0,-0,-0,-0,-0,-0
2,-0,0,3,1,-0,-0,-0,-1,-0,-0,...,-0,-0,-0,-0,-0,-0,-0,-0,-0,-0
3,-0,1,-0,-1,-0,-0,-0,2,-0,-0,...,-0,-0,-0,-0,-0,-0,-0,-0,-0,-0
4,-0,0,-0,1,-0,-0,-0,-1,-0,-0,...,-0,-0,-0,-0,-0,-0,-0,-0,-0,-0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17971,-0,-0,-0,-1,2,-0,-0,-1,-0,2,...,-0,-0,-0,-0,-0,-0,-0,-0,-0,-0
17972,-0,0,-0,-1,-0,-0,-0,-1,-0,-0,...,-0,-0,-0,-0,-0,-0,-0,-0,-0,-0
17973,-0,1,-0,-1,-0,-0,-0,-1,5,-0,...,-0,-0,-0,-0,-0,-0,-0,-0,-0,-0
17974,-0,-0,-0,-1,-0,-0,-0,-1,-0,2,...,-0,-0,-0,-0,-0,-0,-0,-0,-0,-0
17975,-0,1,-0,-1,2,-0,-0,-1,-0,-0,...,-0,-0,-0,-0,-0,-0,-0,-0,-0,-0

 ## Separate the Features (X) from the Target (y)

In [6]:

X = df.drop(columns="Good_Movie")

 ## Split our data into training and testing

In [7]:


from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, 
                                                    y, 
                                                    random_state=1, 
                                                    stratify=y)
X_train.shape

(13482, 12452)

 ## Create a decision_tree Model

In [8]:
# Initial imports
import pandas as pd
from pathlib import Path
from sklearn import tree
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

In [9]:
# Creating StandardScaler instance
scaler = StandardScaler()

In [10]:
# Fitting Standard Scaller
X_scaler = scaler.fit(X_train)

In [11]:
# Scaling data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [12]:
# Creating the decision tree classifier instance
model = tree.DecisionTreeClassifier()

In [13]:
# Fitting the model
model = model.fit(X_train_scaled, y_train)

In [14]:
# Making predictions using the testing data
predictions = model.predict(X_test_scaled)

In [15]:
# Calculating the confusion matrix
cm = confusion_matrix(y_test, predictions)
cm_df = pd.DataFrame(
    cm, index=["Actual 0", "Actual 1"], columns=["Predicted 0", "Predicted 1"]
)

# Calculating the accuracy score
acc_score = accuracy_score(y_test, predictions)

In [16]:
# Displaying results
print("Confusion Matrix")
display(cm_df)
print(f"Accuracy Score : {acc_score}")
print("Classification Report")
print(classification_report(y_test, predictions))

Confusion Matrix

          Predicted 0  Predicted 1
Actual 0         3597          297
Actual 1          386          214

Accuracy Score : 0.8480195816644415
Classification Report
              precision    recall  f1-score   support

       False       0.90      0.92      0.91      3894
        True       0.42      0.36      0.39       600

    accuracy                           0.85      4494
   macro avg       0.66      0.64      0.65      4494
weighted avg       0.84      0.85      0.84      4494